export const skills = [
  {
    name: "Development",
    icon: "fa-code",
    skills: [
      {
        name: "Python",
        likes: 0,
        icon: "devicon-python-plain",
        level: 8,
        classes: "none",
      },
      {
        name: "Javascript/Typescript",
        likes: 0,
        icon: "devicon-typescript-plain",
        level: 10,
        classes: "none",
      },
      {
        name: "Node",
        likes: 0,
        icon: "devicon-nodejs-plain-wordmark",
        level: 7,
        classes: "none",
      },
      {
        name: "PostgreSQL",
        likes: 0,
        icon: "devicon-postgresql-plain",
        level: 5,
        classes: "none",
      },
      {
        name: "PHP",
        likes: 0,
        icon: "devicon-php-plain",
        level: 7,
        classes: "none",
      },
      {
        name: "HTML5/CSS3",
        likes: 0,
        icon: "devicon-html5-plain",
        level: 10,
        classes: "none",
      },
    ],
  },
  {
    name: "Frameworks",
    icon: "fa-gears",
    skills: [
      {
        name: "React",
        likes: 0,
        icon: "devicon-react-original",
        level: 10,
        classes: "none",
      },
      {
        name: "Angular",
        likes: 0,
        icon: "devicon-angular-plain",
        level: 9,
        classes: "none",
      },
      {
        name: "Express",
        likes: 0,
        icon: "devicon-express-original",
        level: 8,
        classes: "none",
      },
      {
        name: "Flask",
        likes: 0,
        icon: "devicon-flask-original",
        level: 8,
        classes: "none",
      },
      {
        name: "RXJS",
        likes: 0,
        icon: "devicon-rxjs-plain",
        level: 6,
        classes: "none",
      },
      {
        name: "Vue",
        likes: 0,
        icon: "devicon-vuejs-plain",
        level: 6,
        classes: "none",
      },
    ],
  },
  {
    name: "Dev Tools",
    icon: "fa-gears",
    skills: [
      {
        name: "Storybook",
        likes: 0,
        icon: "devicon-storybook-plain",
        level: 8,
        classes: "none",
      },
      {
        name: "Vite",
        likes: 0,
        icon: "devicon-vite-original",
        level: 8,
        classes: "none",
      },
      {
        name: "Git",
        likes: 0,
        icon: "devicon-git-plain",
        level: 9,
        classes: "none",
      },
      {
        name: "Webpack",
        likes: 0,
        icon: "devicon-webpack-plain",
        level: 8,
        classes: "none",
      },
    ],
  },
  {
    name: "Dev ops",
    icon: "fa-gears",
    skills: [
      {
        name: "Azure",
        likes: 0,
        icon: "devicon-azure-plain",
        level: 6,
        classes: "none",
      },
      {
        name: "Github Actions",
        likes: 0,
        icon: "devicon-githubactions-plain",
        level: 7,
        classes: "none",
      },
    ],
  },
  {
    name: "Design",
    icon: "fa-pencil",
    skills: [
      {
        name: "Photoshop",
        likes: 0,
        icon: "devicon-photoshop-plain",
        level: 8,
        classes: "none",
      },
      {
        name: "Illustrator",
        likes: 0,
        icon: "devicon-illustrator-plain",
        level: 7,
        classes: "none",
      },
      {
        name: "Bootstrap",
        likes: 0,
        icon: "devicon-bootstrap-plain",
        level: 9,
        classes: "none",
      },
      {
        name: "Figma",
        likes: 0,
        icon: "devicon-figma-plain",
        level: 7,
        classes: "none",
      },
    ],
  },
];
