import { Project } from "./types";

export const projects: Project[] = [
  {
    employer: "faro",
    name: "Faro Study Designer ",
    id: "1",
    img: "/images/projects/faro/dark_spiral.jpg",
    quotes: [],
    skills: [
      "2",
      "3",
      "4",
      "5",
      "7",
      "8",
      "9",
      "11",
      "13",
      "15",
      "16",
      "17",
      "20",
      "23",
    ],
  },
  {
    employer: "various",
    name: "Various Inc Viewer",
    id: "2",
    img: "/images/projects/various/streamer.jpg",
    quotes: [],
    skills: ["2", "3", "7", "8", "9", "10", "13", "17", "18", "21"],
  },
  {
    employer: "faro",
    name: "Faro Data Analytics Dashboard POC",
    id: "5",
    img: "/images/projects/faro/clinical-data.jpg",
    quotes: [],
    skills: ["1", "12", "17"],
  },
  {
    employer: "faro",
    name: "Faro B2C SSO Implementation",
    id: "6",
    img: "/images/projects/faro/lock.jpg",
    quotes: [],
    skills: ["19", "20"],
  },
  {
    employer: "independent",
    name: "San Anselmo City Plan Website",
    previewImgs: ["/images/projects/independent/san_anselmo_preview.png"],
    id: "3",
    img: "/images/projects/independent/downtown.jpg",
    quotes: [],
    skills: ["6", "7", "8", "17", "18", "23"],
  },
  {
    employer: "launchBrigade",
    name: "Launch Brigade Website",
    id: "4",
    img: "/images/projects/launch-brigade/rocket.jpg",
    quotes: [],
    skills: ["6", "7", "8", "17", "18", "21", "22", "23"],
  },
  {
    employer: "independent",
    name: "LotLinx Website",
    id: "7",
    img: "/images/projects/independent/car.jpg",
    quotes: [// {text: "A real good time all around.",author: "Cole Short"},         
    ],
    previewVideos: [
      "/videos/lotlinx_preview.mov",
      "/videos/lotlinx_preview2.mov",
    ],
    skills: ["6", "7", "8"],
  },
  {
    employer: "independent",
    name: "Metafold 3D MVP",
    id: "8",
    img: "/images/projects/independent/3dshapes.jpg",
    quotes: [],
    skills: ["3", "7", "8", "9"],
  },
  {
    employer: "mobian",
    id: "9",
    img: "/images/projects/mobian/mobian1.png",
    name: "Persona & Channel Intelligence",
    quotes: [],
    skills: ["1", "2", "3", "5", "9", "17", "24", "25", "26", "27", "28", "29", "33"],
  },
  {
    employer: "mobian",
    id: "10",
    img: "/images/projects/mobian/mobian2.png",
    name: "Context Ingestion & Brand-Safety Tooling",
    quotes: [],
    skills: ["1", "5", "17", "26", "28", "29", "32", "35", "37"],
  },
  {
    employer: "mobian",
    id: "11",
    img: "/images/projects/mobian/mobian3.png",
    name: "Advertising Operations & Reporting Integrations",
    quotes: [],
    skills: ["1", "2", "3", "5", "9", "17", "24", "25", "26", "28", "30", "31"],
  },
  {
    employer: "mobian",
    id: "12",
    img: "/images/projects/mobian/mobian4.png",
    name: "Platform Engineering, Testing & Product Infrastructure",
    quotes: [],
    skills: [ "1", "2", "3", "9", "15", "17", "20", "24", "25", "26", "27", "28", "29", "32", "33", "34", "35", "36", "37",],
  },
  {
    employer: "mobian",
    id: "13",
    img: "/images/projects/mobian/mobian5.png",
    name: "Frontend UI & Design System",
    quotes: [],
    skills: ["2","3","7","8","9","15","17","20","23","24","25","33","34","36",]
  },
];
