import { Skill, SkillType } from "./types";

export const skillTypes: SkillType[] = [
  {
    name: "Development",
    icon: "fa-code",
    id: "1",
    img: "/imgs/coding_skills.jpg",
  },
  {
    name: "Frameworks",
    icon: "fa-gears",
    id: "2",
    img: "/imgs/framework.jpg",
  },
  {
    name: "Dev Tools",
    icon: "fa-gears",
    id: "3",
    img: "/imgs/tools.jpg",
  },
  {
    name: "IT",
    icon: "fa-gears",
    id: "4",
    img: "/imgs/it_skills.jpg",
  },
  {
    name: "Design",
    icon: "fa-pencil",
    id: "5",
    img: "/imgs/design_skills.jpg",
  },
];

export const skills: Skill[] = [
  {
    name: "Python",
    id: "1",
    type: "1",
    likes: 0,
    icon: "devicon-python-plain",
    level: 8,
    classes: "none",
    projects: [{ name: "Faro Data Analytics Dashboard POC", id: "5" }],
  },
  {
    name: "Javascript",
    id: "2",
    type: "1",
    likes: 0,
    icon: "devicon-javascript-plain",
    level: 10,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Various Inc Viewer", id: "2" },
    ],
  },
  {
    name: "Typescript",
    id: "3",
    type: "1",
    likes: 0,
    icon: "devicon-typescript-plain",
    level: 10,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Various Inc Viewer", id: "2" },
      { name: "Metafold 3D MVP", id: "8" },
    ],
  },
  {
    name: "Node",
    id: "4",
    type: "1",
    likes: 0,
    icon: "devicon-nodejs-plain-wordmark",
    level: 7,
    classes: "none",
    projects: [{ name: "Faro Study Designer ", id: "1" }],
  },
  {
    name: "PostgreSQL",
    id: "5",
    type: "1",
    likes: 0,
    icon: "devicon-postgresql-plain",
    level: 5,
    classes: "none",
    projects: [{ name: "Faro Study Designer ", id: "1" }],
  },
  {
    name: "PHP",
    id: "6",
    type: "1",
    likes: 0,
    icon: "devicon-php-plain",
    level: 7,
    classes: "none",
    projects: [
      { name: "Launch Brigade Website", id: "4" },
      { name: "San Anselmo City Plan Website", id: "3" },
      { name: "LotLinx Website", id: "7" },
    ],
  },
  {
    name: "HTML5",
    id: "7",
    type: "1",
    likes: 0,
    icon: "devicon-html5-plain",
    level: 10,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Various Inc Viewer", id: "2" },
      { name: "San Anselmo City Plan Website", id: "3" },
      { name: "Launch Brigade Website", id: "4" },
      { name: "LotLinx Website", id: "7" },
      { name: "Metafold 3D MVP", id: "8" },
    ],
  },
  {
    name: "CSS/SCSS",
    id: "8",
    type: "1",
    likes: 0,
    icon: "devicon-sass-plain",
    level: 10,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Various Inc Viewer", id: "2" },
      { name: "San Anselmo City Plan Website", id: "3" },
      { name: "Launch Brigade Website", id: "4" },
      { name: "LotLinx Website", id: "7" },
      { name: "Metafold 3D MVP", id: "8" },
    ],
  },

  {
    name: "React",
    id: "9",
    type: "2",
    likes: 0,
    icon: "devicon-react-original",
    level: 10,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Various Inc Viewer", id: "2" },
      { name: "Metafold 3D MVP", id: "8" },
    ],
  },
  {
    name: "Angular",
    id: "10",
    type: "2",
    likes: 0,
    icon: "devicon-angular-plain",
    level: 9,
    classes: "none",
    projects: [{ name: "Various Inc Viewer", id: "2" }],
  },
  {
    name: "Express",
    id: "11",
    type: "2",
    likes: 0,
    icon: "devicon-express-original",
    level: 8,
    classes: "none",
    projects: [{ name: "Faro Study Designer ", id: "1" }],
  },
  {
    name: "Flask",
    id: "12",
    type: "2",
    likes: 0,
    icon: "devicon-flask-original",
    level: 8,
    classes: "none",
    projects: [{ name: "Faro Data Analytics Dashboard POC", id: "5" }],
  },
  {
    name: "RXJS",
    id: "13",
    type: "2",
    likes: 0,
    icon: "devicon-rxjs-plain",
    level: 6,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Various Inc Viewer", id: "2" },
    ],
  },
  {
    name: "Vue",
    id: "14",
    type: "2",
    likes: 0,
    icon: "devicon-vuejs-plain",
    level: 6,
    classes: "none",
    projects: [],
  },

  {
    name: "Storybook",
    id: "15",
    type: "3",
    likes: 0,
    icon: "devicon-storybook-plain",
    level: 8,
    classes: "none",
    projects: [{ name: "Faro Study Designer ", id: "1" }],
  },
  {
    name: "Vite",
    id: "16",
    type: "3",
    likes: 0,
    icon: "devicon-vite-original",
    level: 8,
    classes: "none",
    projects: [{ name: "Faro Study Designer ", id: "1" }],
  },
  {
    name: "Git",
    id: "17",
    type: "3",
    likes: 0,
    icon: "devicon-git-plain",
    level: 9,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Various Inc Viewer", id: "2" },
      { name: "San Anselmo City Plan Website", id: "3" },
      { name: "Launch Brigade Website", id: "4" },
      { name: "Faro Data Analytics Dashboard POC", id: "5" },
    ],
  },
  {
    name: "Webpack",
    id: "18",
    type: "3",
    likes: 0,
    icon: "devicon-webpack-plain",
    level: 8,
    classes: "none",
    projects: [
      { name: "Various Inc Viewer", id: "2" },
      { name: "San Anselmo City Plan Website", id: "3" },
      { name: "Launch Brigade Website", id: "4" },
    ],
  },
  {
    name: "Azure",
    id: "19",
    type: "4",
    likes: 0,
    icon: "devicon-azure-plain",
    level: 6,
    classes: "none",
    projects: [{ name: "Faro B2C SSO Implementation", id: "6" }],
  },
  {
    name: "Github Actions",
    id: "20",
    type: "4",
    likes: 0,
    icon: "devicon-githubactions-plain",
    level: 7,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "Faro B2C SSO Implementation", id: "6" },
    ],
  },
  {
    name: "Photoshop",
    id: "21",
    type: "5",
    likes: 0,
    icon: "devicon-photoshop-plain",
    level: 8,
    classes: "none",
    projects: [
      { name: "Various Inc Viewer", id: "2" },
      { name: "Launch Brigade Website", id: "4" },
    ],
  },
  {
    name: "Bootstrap",
    id: "22",
    type: "5",
    likes: 0,
    icon: "devicon-bootstrap-plain",
    level: 9,
    classes: "none",
    projects: [{ name: "Launch Brigade Website", id: "4" }],
  },
  {
    name: "Figma",
    id: "23",
    type: "5",
    likes: 0,
    icon: "devicon-figma-plain",
    level: 7,
    classes: "none",
    projects: [
      { name: "Faro Study Designer ", id: "1" },
      { name: "San Anselmo City Plan Website", id: "3" },
      { name: "Launch Brigade Website", id: "4" },
    ],
  },
];
